baseURL: "https://aananyevskiy.github.io/" 
title: Alexey Ananyevskiy
#paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Notes
          url: notes/
          weight: 3
        - name: Papers
          url: papers/
          weight: 2
        - name: Contacts
          url: contacts/
          weight: 4
        - name: CV
          url: cv/
          weight: 1 
        - name: Other
          url: other/
          weight: 5

params:
    description: "I am a mathematician currently based in Munich and supported by DFG. My research focuses mostly on cohomological and topological methods in algebraic geometry."
    author: Alexey Ananyevskiy
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    social: true
    profileMode:
          enabled: true
          title: Alexey Ananyevskiy
          subtitle: "I am a mathematician currently based in Munich and supported by DFG, before I was a senior researcher at the Steklov Institute and a deputy director of the Euler International Mathematical Institute in St. Petersburg. My research focuses mostly on cohomological and topological methods in algebraic geometry, and I am interested in motivic homotopy theory, K-theory and algebraic groups."
          #imageUrl: "photo.jpg"
          imageWidth: 360
          imageHeight: 360
          imageTitle: Alexey Ananyevskiy
          buttons:
            - name: CV
              url: cv/
            - name: Papers
              url: papers/
            - name: Notes
              url: notes/
            - name: Contacts
              url: contacts/
            - name: Other
              url: other/
          #  - name: Archive
          #    url: archive/
          #  - name: Blog
          #    url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

#    socialIcons:
#        - name: CV
#          url: cv.pdf
#        - name: Email
#          url: mailto:ananyevskiy@math.lmu.de
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
#        - name: Location
#          url: location/
        #- name: Office Hours
       #   url: officehours/
#        - name: arXiv
#          url: https://arxiv.org/search/?searchtype=author&query=Ananyevskiy%2C+A
        #- name: GitHub
        #  url: https://github.com/pmichaillat
        #- name: Substack
        #  url: https://pmichaillat.substack.com
       # - name: YouTube
       #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
      #  - name: Twitter
       #   url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alexey Ananyevskiy"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2